CREATE TABLE cartas (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  ataque VARCHAR(255) NOT NULL,
  defesa VARCHAR(255) NOT NULL,
  tipo VARCHAR(255) NOT NULL,
  descricao VARCHAR(255) NOT NULL
)
